### ISSUE TITLE
Example app dies with error - Assignment to constant variable

### ISSUE THREAD

**Issue by jamsyoung** [cnnlabs/cnn-hapi#8]
Happening on `develop` branch, and probably `master`. 

```
$ NODE_ENV=production DEBUGMETRICS=1 ENVIRONMENT=production HOSTEDGRAPHITE_APIKEY=OMITTED DEBUG=* PORT=5000 node example/app.js
  metrics Options passed to Metrics {"app":"hapi-demo-app","flushEvery":2000} +0ms
  metrics We are Logging- true +2ms
  metrics { app: 'hapi-demo-app', flushEvery: 2000 } +1ms
/Users/jyoung/dev/cnn-hapi/main.js:109
        metricsProvider = options.metrics.provider;
                        ^

TypeError: Assignment to constant variable.
    at module.exports.options (/Users/jyoung/dev/cnn-hapi/main.js:109:25)
    at Object.<anonymous> (/Users/jyoung/dev/cnn-hapi/example/app.js:16:28)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

**Comment by jamsyoung** [comment]
Fixed in 0.3.7
